### ISSUE TITLE
panic when proxying binary data

### ISSUE THREAD

**Issue by rtyler** [dvkt/phroxy#1]
Was just dorking around with `phroxy` and crashed it pretty easily when trying to open an image file:

```
│ GET /style.css HTTP/1.1
└ 200 OK: style.css
┌ Connection from 127.0.0.1:35904
┌ Connection from 127.0.0.1:35906
│
│ GET /gopher://gopher.floodgap.com/p/overbite/ss/AndroidQ-Address%20bar%20and%20image%20support.png HTTP/1.1
└ 200 OK
┌ Connection from 127.0.0.1:35916
thread '<unnamed>' panicked at 'byte index 210557 is not a char boundary; it is inside '�' (bytes 210555..210558) of `�PNG

IHDR"D��)lsBIT|d� IDATx��wx���3��M%�P�PB�it��Ai*��
�r��UAA��䂀t�.�JQz���^$�R�����ɐ@�	\���<���9�=g�s�Q��'N#����'N��ȉ'��"r���cǩ�`[...]', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/str/mod.rs:1920:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    13461 abort (core dumped)  ./target/release/phroxy
```

This is on the latest `HEAD`: `da717023dd741e17af51e4754781e51827f66d99`

**Comment by xvxx** [comment]
Whoops sorry about that. I've got it showing an error message now when it encounters a gopher item type it doesn't know how to render. Maybe in the future I can make small PNGs and GIFs work, but as of a1e3659ba221c1b8e42f077c6f84b5c196269ee4 it should at least not crash anymore. Thank you for reporting!
