### ISSUE TITLE
Binary types rendered on phroxy.net

### ISSUE THREAD

**Issue by rtyler** [dvkt/phroxy#2]
Here's a link to a video (type 9) in my gopher space: https://phroxy.net/gopher://gopher.brokenco.de/9/videos/2020-pagerduty-testimonial/Scribd%20Uses%20PagerDuty%20to%20Support%20Growth%20of%20Their%20Massive%20Digital%20Library-7yn0PZ_yMnM.mkv

(From https://phroxy.net/gopher://gopher.brokenco.de/1/videos/2020-pagerduty-testimonial)

It ends up being rendered :laughing: 

Based on #1 I was kind of curious whether I would crash your server or not :smiling_imp:

**Comment by xvxx** [comment]
I just updated phroxy.net with the fix for #1, so it should show an error message when you click on that video link now. I also added autolinking to info lines, so the YouTube URL should be a real link now too. Thanks once again for the bug report!
